item = input()
c = int(input())
v = int(input())
m = int(input())
print('Чек')
print(f'{item} - {v}кг - {c}руб/кг')
print(f'Итого: {v * c}руб')
print(f'Внесено: {m}руб')
print(f'Сдача: {m - v * c}руб')
